name: Android CI (manual)

on:
  workflow_dispatch:
    inputs:
      buildType:
        description: "debug or release"
        required: true
        default: "debug"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: ${{ github.event.inputs.buildType }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - uses: android-actions/setup-android@v3
      - run: yes | sdkmanager --licenses
      - run: chmod +x ./gradlew

      - name: Build
        run: |
          if [ "$BUILD_TYPE" = "release" ]; then
            ./gradlew assembleRelease --stacktrace
          else
            ./gradlew assembleDebug --stacktrace
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ env.BUILD_TYPE }}
          path: app/build/outputs/apk/${{ env.BUILD_TYPE }}/*.apk
